### ISSUE TITLE
Building in Indigo

### ISSUE THREAD

**Issue by droter** [ros-drivers/nmea_comms#3]
Hi,

I downloaded the package and tried to build in indigo on ubuntu 14.04 LTS.

I am getting this error:
-- ==> add_subdirectory(nmea_comms)
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "nmea_msgs" with
  any of the following names:

```
nmea_msgsConfig.cmake
nmea_msgs-config.cmake
```

  Add the installation prefix of "nmea_msgs" to CMAKE_PREFIX_PATH or set
  "nmea_msgs_DIR" to a directory containing one of the above files.  If
  "nmea_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  nmea_comms/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!

Thanks,

Matt

**Comment by droter** [comment]
I ran rosdep check and was missing a package nmea_msgs.  Installed and it is building now.

**Comment by HelloDavid2020** [comment]
cd ~/robot_ws
rosdep check --from-path src --ignore-src -r -y
rosdep install --from-path src --ignore-src -r -y
