### ISSUE TITLE
Plan for noetic?

### ISSUE THREAD

**Issue by alduxvm** [ros-drivers/nmea_comms#8]
Hi!

Is there a plan to add noetic support?

thanks!

**Comment by tkazik** [comment]
+1, would love to see that as well!

**Comment by Tobias-Fischer** [comment]
+1

**Comment by Tobias-Fischer** [comment]
Ping @mikepurvis - is there anything we can help to make this release happen? It works without any issues when built from sources.

**Comment by tonybaltovski** [comment]
Release here: https://github.com/ros/rosdistro/pull/28062

**Comment by Tobias-Fischer** [comment]
Thank you!
